module.exports = {
    "login": "hassonor",
    "id": 70104184,
    "node_id": "MDQ6VXNlcjcwMTA0MTg0",
    "avatar_url": "https://avatars.githubusercontent.com/u/70104184?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/hassonor",
    "html_url": "https://github.com/hassonor",
    "followers_url": "https://api.github.com/users/hassonor/followers",
    "following_url": "https://api.github.com/users/hassonor/following{/other_user}",
    "gists_url": "https://api.github.com/users/hassonor/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/hassonor/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/hassonor/subscriptions",
    "organizations_url": "https://api.github.com/users/hassonor/orgs",
    "repos_url": "https://api.github.com/users/hassonor/repos",
    "events_url": "https://api.github.com/users/hassonor/events{/privacy}",
    "received_events_url": "https://api.github.com/users/hassonor/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Or Hasson",
    "company": null,
    "blog": "https://www.linkedin.com/in/orhasson/",
    "location": "Israel",
    "email": null,
    "hireable": true,
    "bio": "Code in my Veins :) \r\n",
    "twitter_username": null,
    "public_repos": 31,
    "public_gists": 0,
    "followers": 36,
    "following": 16,
    "created_at": "2020-08-23T15:32:59Z",
    "updated_at": "2022-05-31T07:00:04Z"
}